name: Deploy my Lamda Function 1#

on:
  push:
      branches:
        - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install lint
      run: |
        cd function
        pip install flake8
    - name: Lint flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --maxline-length=127 --statistics

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run:  |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
    - name: Create zip bundle
      run:  |
           cd function
           zip -r ../${{github.sha}}.zip .
    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
         name: zipped-bundle
         path: ${{ github.sha }}.zip
          
      
